[build]
  publish = "public"
  command = "make production-build"

[build.environment]
  HUGO_VERSION = "0.115.2"
  NODE_VERSION = "16"
  GO_VERSION = "1.18"

[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "make preview-build"

[context.branch-deploy]
  command = "make branch-build"

[[headers]]
  for = "/*"
  [headers.values]
  X-Frame-Options = "SAMEORIGIN"
  Content-Security-Policy = "frame-ancestors 'self'"

[[redirects]]
from = "/en/flux/*"
to = "/en/flux/404.html"
status = 404

[[redirects]]
	from = "/*"
	to = "/404/"
	status = 404
